# Generated by Django 4.2.2 on 2023-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=127, verbose_name="word")),
                ("frequency", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
